### ISSUE TITLE
Pressing enter on the markdown editor scrolls to top

### ISSUE THREAD

**Issue by elit-altum** [accordproject/web-components#91] opened 2020-05-17 17:20 UTC
# Bug Report 🐛

Upon pressing enter on the markdown editor storybook demo, the editor scrolls to the top.

## Expected Behavior

The editor should be at its place.

## Possible Solution

I think this could be an issue similar to https://github.com/accordproject/markdown-editor/pull/388

## Steps to Reproduce

1. Visit the Demo
2. Place cursor on the editor
3. Press Enter
4. The screen will scroll to the top

### Desktop
 - OS: Windows 10
 - Browser: Firefox developer edition

## Screenshot
![Scroll-error](https://user-images.githubusercontent.com/41413622/82155191-b81f6800-9890-11ea-939b-87504ff3b94f.gif)

**Comment by elit-altum** [comment] 2020-05-17 17:21
@irmerk is this expected behavior?
 And it also seems like the editor is crashing if I use any shortcuts like Ctrl + K etc. Are you able to reproduce this ?

**Comment by irmerk** [comment] 2020-05-18 13:02
Yeah I can reproduce it. However, I can't reproduce the shortcuts crashing the editor.

**Comment by justinclanglinais** [comment] 2020-08-25 18:35
Hi, I can't reproduce this error.

**Comment by irmerk** [comment] 2020-08-25 19:24
I can't either. Unsure what changed since May. Closing.

**Closed by irmerk** 2020-08-25 19:24 UTC
Labels: Difficulty: Medium, Good First Issue :octocat:, Package: Markdown Editor ⌨️, Type: Bug 🐛
